### PR TITLE
Update package.json to work on windows with git bash.

### PR DESCRIPTION
**Pull request by facuxt**
New commands:
npm run startWin

and 

npm run devWin

Modified readme aswell to comply with this.

### CODE REVIEW

**Comment by facuxt** [comment]
@davellanedam

**Comment by davellanedam** [comment]
Hello, thank you for the pull request, I'm sorry for the late response, been busy.

I don't think we need to create 2 more commands for windows, wouldn't be better to mention this in the README.md ? What do you think?

**Comment by facuxt** [comment]
sorry for the delay... I think this should be solved within logic in start script... maybe some identification of the system (but i dont know how to do that exactly, so i just added those two commands)... 

I think its good enough, so newcomers can run and maintain compatibility of what you have here in this repo.


oh.. and MANY thanks for this... is awesome and a real time saver!!!

**Comment by Kumarsuman21** [comment]
I have used "cross-env" module to solve this issue and create a pull request against this https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/pull/139

**Comment by davellanedam** [comment]
Solved using https://github.com/davellanedam/node-express-mongodb-jwt-rest-api-skeleton/pull/139

**Pull request closed without merging**
