### PR TITLE
I suggest some minor fixes

### PR DESCRIPTION
**Pull request by aydincandan**
This is my first try, may I be missing something?

### CODE REVIEW

**Comment by davellanedam** [comment]
Hello, thanks for your contribution, but this will work for windows only, the reality is that production servers are linux, so the “rd” command will fail when running the CI, and the same applies for the production start script, you never use just node, you use pm2 which is far better.

**Comment by aydincandan** [comment]
for (add to Turkish locales)  : Yes this is a skeleton only project so I retract it as I don't think it's necessary.

**Comment by aydincandan** [comment]
I'm ashamed of myself for hearing pm2 today.

**Comment by davellanedam** [comment]
Thanks again @aydincandan, I can add the Turkish locale, but everything else I’m afraid won’t make it, because of the reasons I gave you before. Please open a new PR against development branch, only with the tr locale and close this PR.

**Pull request closed without merging**
